version: '3.8'

services:
  # Kafka setup
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Base de données PostgreSQL pour auth-service
  auth-postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      - POSTGRES_DB=UserDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Imad2002
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d UserDb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Base de données PostgreSQL pour catalog-service
  catalog-postgres:
    image: postgres:15-alpine
    container_name: catalog-postgres
    environment:
      - POSTGRES_DB=catalog_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Imad2002
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalog_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Base de données PostgreSQL pour questionnaire-service
  questionnaire-postgres:
    image: postgres:15-alpine
    container_name: questionnaire-postgres
    environment:
      - POSTGRES_DB=evaling
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Imad2002
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5434:5432"
    volumes:
      - questionnaire_postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d evaling"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # pgAdmin - Database Management Interface
  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices-network
    depends_on:
      auth-postgres:
        condition: service_healthy
      catalog-postgres:
        condition: service_healthy
      questionnaire-postgres:
        condition: service_healthy
    restart: unless-stopped

  # Authentication service
  auth-service:
    image: ${REGISTRY}/${IMAGE_OWNER}/${IMAGE_PREFIX}:auth-service-${IMAGE_TAG:-latest}
    container_name: authentication-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=auth-postgres
      - DB_PORT=5432
      - DB_NAME=UserDb
      - DB_USER=postgres
      - DB_PASSWORD=Imad2002
      - JWT_TOKEN=QmFzZTY0IGVuY29kZWQgNjQgYnl0ZSBrZXkgZm9yIEpXVCBIUzUxMiBhbGdvcml0aG0gMTIzNDU2Nzg5MCEjQCQlXiYqKClfKw
      - JWT_ISSUER=auth-service
      - JWT_AUDIENCE=formation-evaluation-app
      - EMAIL_SENDER=imade17ma@gmail.com
      - EMAIL_SENDER_NAME=Imad
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_ENABLE_SSL=true
      - SMTP_USERNAME=imade17ma@gmail.com
      - SMTP_PASSWORD=fsrpmqhytbeoacnc
    depends_on:
      auth-postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/wwwroot/uploads/profiles
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Catalog service
  catalog-service:
    image: ${REGISTRY}/${IMAGE_OWNER}/${IMAGE_PREFIX}:catalog-service-${IMAGE_TAG:-latest}
    container_name: catalog-service
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=catalog-postgres;Database=catalog_db;Username=postgres;Password=Imad2002
      - Jwt__Token=QmFzZTY0IGVuY29kZWQgNjQgYnl0ZSBrZXkgZm9yIEpXVCBIUzUxMiBhbGdvcml0aG0gMTIzNDU2Nzg5MCEjQCQlXiYqKClfKw
      - Jwt__Issuer=auth-service
      - Jwt__Audience=formation-evaluation-app
    depends_on:
      catalog-postgres:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Service de questionnaire (Evaluation Service)
  questionnaire-service:
    image: ${REGISTRY}/${IMAGE_OWNER}/${IMAGE_PREFIX}:questionnaire-service-${IMAGE_TAG:-latest}
    container_name: questionnaire-service
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Postgres=Host=questionnaire-postgres;Port=5432;Username=postgres;Password=Imad2002;Database=evaling
      - JWT_TOKEN=QmFzZTY0IGVuY29kZWQgNjQgYnl0ZSBrZXkgZm9yIEpXVCBIUzUxMiBhbGdvcml0aG0gMTIzNDU2Nzg5MCEjQCQlXiYqKClfKw
      - JWT_ISSUER=auth-service
      - JWT_AUDIENCE=formation-evaluation-app
    depends_on:
      questionnaire-postgres:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Statistics service
  statistics-service:
    image: ${REGISTRY}/${IMAGE_OWNER}/${IMAGE_PREFIX}:statistics-service-${IMAGE_TAG:-latest}
    container_name: statistics-service
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - QUESTIONNAIRE_SERVICE_URL=http://questionnaire-service:8080
      - AUTH_SERVICE_URL=http://auth-service:8080
      - CATALOG_SERVICE_URL=http://catalog-service:8080
    depends_on:
      auth-service:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
      questionnaire-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # API Gateway
  api-gateway:
    image: ${REGISTRY}/${IMAGE_OWNER}/${IMAGE_PREFIX}:api-gateway-${IMAGE_TAG:-latest}
    container_name: api-gateway
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - AUTH_SERVICE_URL=http://auth-service:8080
      - CATALOG_SERVICE_URL=http://catalog-service:8080
      - QUESTIONNAIRE_SERVICE_URL=http://questionnaire-service:8080
      - STATISTICS_SERVICE_URL=http://statistics-service:8080
    depends_on:
      kafka:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
      questionnaire-service:
        condition: service_healthy
      statistics-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 150s

# Configuration du réseau partagé entre microservices
networks:
  microservices-network:
    driver: bridge
    name: microservices-net

# Persistent volumes
volumes:
  postgres_data:
    driver: local
  catalog_postgres_data:
    driver: local
  questionnaire_postgres_data:
    driver: local
  pgadmin_data:
    driver: local
